### ISSUE TITLE
Criar Style Guide do projeto

### ISSUE THREAD

**Issue by fepas** [fga-gpp-mds/dulce-app#111]
Nessa issue será realizado:
- Produção do documento _Style Guide_ do projeto.

Critérios de aceitação:
- Ser entendível e aplicável ao código do projeto.

**Comment by egewarth** [comment]
@fga-gpp-mds/mds-agr , faltou algumas labels, vou adicionar aqui e dps vcs ficam ligados nela.

**Comment by egewarth** [comment]
@fga-gpp-mds/mds-agr, vocês não vão confeccionar o documento de style guide todo, vocês vão criar um linkando o do airbnb e vão aplicar no código.
